import { COLOR_BASE_CREAM, COLOR_INK_PRIMARY, COLOR_INK_SECONDARY } from './ringColors'

export const DISPLAY_FRAME_BG = COLOR_BASE_CREAM
export const DISPLAY_FRAME_BORDER = COLOR_INK_PRIMARY

export const DISPLAY_BG_GLASS = '#CFE6DF'
export const DISPLAY_BG_PLASTIC = '#E4E8D6'
export const DISPLAY_BG_METAL = '#D9DEE3'

export const DISPLAY_TEXT = COLOR_INK_SECONDARY
export const DISPLAY_TEXT_SECONDARY = '#4F4D47'
export const DISPLAY_TEXT_PHOSPHOR_PRIMARY = '#8FCFC2'
export const DISPLAY_TEXT_PHOSPHOR_SECONDARY = '#74B3A8'

export const DISPLAY_BG_MINT = '#BFD8D2'
export const DISPLAY_TEXT_TEAL = '#6AAFA3'
export const DISPLAY_TEXT_TEAL_DARK = '#4A8B7E'
export const DISPLAY_OUTLINE_BROWN = '#5A3A24'
export const DISPLAY_SHADOW = 'rgba(0,0,0,0.16)'
export const DISPLAY_ANIMATION_DURATION = 150
